### ISSUE TITLE
www.polyvariant.org does not show the webpage

### ISSUE THREAD

**Issue by LazyBun** [polyvariant/home#1]
Steps to reproduce:

1. Go to `www.polyvariant.org`
2. Does not work.
3. `polyvariant.org` does work.
4. What do

**Comment by kubukoz** [comment]
DNS sorcery!

**Comment by majk-p** [comment]
`www.polyvariant.org` pointed to the default OVH webserver. I've updated the the DNS zone, the change should be soon visible.

**Comment by majk-p** [comment]
```shell
majk@phoenix:~$ dig +short polyvariant.org
51.89.167.71
majk@phoenix:~$ dig +short www.polyvariant.org
51.89.167.71
```
Fixed, visiting both https://www.polyvariant.org and https://polyvariant.org seems to work fine
